### ISSUE TITLE
Complex LaTeX strings in documentation

### ISSUE THREAD

**Issue by andreasbuhr** [tobias-loew/flags#10]
In the documentation is the following string

```
\({\raise.17ex\hbox{$\scriptstyle\sim$}}\)
```

probably this is beyond the capabilities of the latex-parsing skills of most people.

**Comment by tobias-loew** [comment]
That was a tough one: the latex-formulas were translate correctly on my local system but failed in html-preview. Somehow htmlpreview.github.io is unable to load the MathJax sources. Changing to raw.githack.com for html-preview solved the problem!
