### ISSUE TITLE
namespace boost::flags::impl::impl

### ISSUE THREAD

**Issue by andreasbuhr** [tobias-loew/flags#11]
There is a namespace "impl" in the namespace "impl". Maybe another scheme is clearer.

https://github.com/tobias-loew/flags/blob/4dee2da594c84e5ab291a7884b6778e83d677f4d/flags.hpp#L253

**Comment by tobias-loew** [comment]
It looks like there is a double nested "impl" namespace, but there isn't. There are currently are three "impl" namespaces:
- line 123 - 137
- line 253 - 401
- line 640 - 662

none is nested within another

**Comment by andreasbuhr** [comment]
right, my brain-parser didn't close the impl at line 137. Bug in my brain-parser.
