### ISSUE TITLE
Godbolt-Example is unstable

### ISSUE THREAD

**Issue by andreasbuhr** [tobias-loew/flags#12]
The linked godbolt example https://godbolt.org/z/bMrfb6Gz5 is unstable:

It uses a branch name to specify the file version, it uses
`#include <https://raw.githubusercontent.com/tobias-loew/flags/main/include/boost/flags.hpp>`
So when someone opens the example in the future, he or she will get errors because the old example will be combined with a new version of flags.hpp.

I would suggest to use a commit-sha to link a specific version of flags.hpp, like for example
`#include <https://raw.githubusercontent.com/tobias-loew/flags/89844be20e43e666a8e2f8a518875b782da001f1/include/boost/flags.hpp>`

That way the godbolt-link will continue working in the future.

**Comment by andreasbuhr** [comment]
My prediction already came true: The linked godbolt example is broken now.

**Comment by tobias-loew** [comment]
You're prediction occurred after I changed the link to a stable version.
I have to check what went wrong.

**Comment by andreasbuhr** [comment]
README.md hasn't changed in a week:

![image](https://github.com/tobias-loew/flags/assets/3892222/4b1870ad-367d-4836-b94e-4f3f70e5fd59)

**Comment by tobias-loew** [comment]
My fault. I forgot to push the changes.
Now it's done.

**Comment by andreasbuhr** [comment]
is fixed.
