### ISSUE TITLE
Unhelpful error messages

### ISSUE THREAD

**Issue by andreasbuhr** [tobias-loew/flags#14]
I tried it in my project. I included flags.hpp and activated it for two enums. However, it gives me a completely unhelpful error message. I get

```
1>------ Build started: Project: Myproject, Configuration: Debug x64 ------
1>Myfile.cpp
1>C:\Mypath\flags.hpp(689,25): error C2338: calling bitwise operator with incompatible enumerations
1>C:\Mypath\flags.hpp(932): message : see reference to class template instantiation 'boost::flags::impl::compatibility_check<T1,T2>' being compiled
1>        with
1>        [
1>            T1=int,
1>            T2=Mynamespace::myenum
1>        ]
1>C:\Mypath\flags.hpp(932): message : see reference to alias template instantiation 'boost::flags::impl::compatibility_check_t<int,Mynamespace::myenum>' being compiled
1>Done building project "Myproject.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

As you can see, the error message does not contain any line number in my source code. Only three line numbers in flags.hpp are referenced. There is no way I can fix it without knowing where it is.

**Comment by tobias-loew** [comment]
Can you post the source, MSVC & C++ standard version, please. In my examples, I always get additional errors pointing to the user source code where the error originates.

**Comment by tobias-loew** [comment]
Hold on, I could figure it out: for unscoped enums, there are poor error meassges.

**Comment by andreasbuhr** [comment]
![image](https://github.com/tobias-loew/flags/assets/3892222/ec9629f8-de75-4185-8839-58b007cb94fe)

**Comment by andreasbuhr** [comment]
Is it maybe possible in the unit tests to require that the offending line number is present in the output?

**Comment by tobias-loew** [comment]
I changed the detection for the usage of incompatible enumerations for binary operators (i.e. at least one of them is enabled, but not both equal (modulo complement-template) or one of the is a pseudo_and_op):
Former, it was a static_assert, which resulted in unhelpful error messages.
Now, those overloads are deleted, which gives error messages that point to the usage in the user-code.
Changes are here
2c4edc51d73a0bff1901e7dc3a6332928c37b473

**Comment by tobias-loew** [comment]
> Is it maybe possible in the unit tests to require that the offending line number is present in the output?

I don't know whether that's possible. It would require capturing stdout or stderr and analyzing the output. That's way beyond b2's `compile-fail` command.

**Comment by andreasbuhr** [comment]
For me this seems to be solved.

**Comment by tobias-loew** [comment]
Required changes merged. Thanks again!
