### ISSUE TITLE
Including flags.hpp leads to errors unrelated to enums

### ISSUE THREAD

**Issue by andreasbuhr** [tobias-loew/flags#16]
Sometimes, including flags.hpp leads to errors which are completely unrelated to enums. See for example the following error message:

```
1>------ Build started: Project: Myproject, Configuration: Debug x64 ------
1>Myfile.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\include\type_traits(468,39): error C2139: 'MyClass': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_convertible_to'
1>C:\Mypath\myfile.h(57): message : see declaration of 'MyClass'
1>C:\Mypath\flags.hpp(417): message : see reference to class template instantiation 'std::is_convertible<E,MyClass>' being compiled
1>        with
1>        [
1>            E=MyClass
1>        ]
1>C:\Mypath\myfile.h(70): message : see reference to class template instantiation 'boost::flags::impl::is_scoped_enum<MyClass>' being compiled
1>Done building project "Myproject.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Using this version of flags.hpp:
https://github.com/tobias-loew/flags/blob/2c4edc51d73a0bff1901e7dc3a6332928c37b473/include/boost/flags.hpp

And this version of MSVC:

![image](https://github.com/tobias-loew/flags/assets/3892222/781523fe-3432-4fe9-899e-01a8b6bee6d4)

**Comment by andreasbuhr** [comment]
To reproduce, try first including flags.hpp, then include Qt5\Win64\include\QtNetwork\qssldiffiehellmanparameters.h

Error points to this code:
```
inline bool operator!=(const QSslDiffieHellmanParameters &lhs, const QSslDiffieHellmanParameters &rhs) noexcept
{
    return !operator==(lhs, rhs);
}
```

**Comment by tobias-loew** [comment]
I've opened a PR https://github.com/tobias-loew/flags/pull/17 with a potential fix.
could not test: downloading Qt5 from github does not find submodules, and installing qt wants my data >:(

**Comment by andreasbuhr** [comment]
I'll test.

You could use Ubuntu in virtual box and then just apt-get install the Qt sources

**Comment by tobias-loew** [comment]
Thanks for the hint. That worked.
Local tests were successful.
I also forgot to push the changes. Now it's done.

**Comment by andreasbuhr** [comment]
For me this seems to be solved.

**Comment by tobias-loew** [comment]
Required changes merged. Thanks again!
