### ISSUE TITLE
Macro BF_NULL violates Boost's naming policy

### ISSUE THREAD

**Issue by andreasbuhr** [tobias-loew/flags#2]
The Boost naming policy in https://www.boost.org/doc/libs/1_33_1/more/lib_guide.htm states:

"Macro (gasp!) names all uppercase and begin with BOOST_."

The macro BF_NULL violates that.

**Comment by tobias-loew** [comment]
I wanted to keep to short, but you're of course right.
removed it (BOOST_FLAGS_NULL  was already present)
also changed BF_AND to BOOST_FLAGS_AND
