### ISSUE TITLE
unscoped enum with unspecified underlying type does not result in compiler error

### ISSUE THREAD

**Issue by andreasbuhr** [tobias-loew/flags#22]
The documentation states:

> But, defining the underlying type for unscoped enumerations is crutial!

If this is the case, would it be possible to generate a compiler error in this case?
I changed the godbolt example to use unscoped enums and not specify an underlying type and use C++17, it compiles just fine:
https://godbolt.org/z/EEK7ePax9

**Comment by tobias-loew** [comment]
The following note explains, why this is a problem. (I added a short hint to the note.)
Furthermore, it is not possible to check whether the underlying type is specified explicitly or deduced. There exists no trait for that.

**Comment by andreasbuhr** [comment]
C++17 && signed underlying type can be detected, right?

**Comment by tobias-loew** [comment]
The underlying type (and signed) can be detected already with C++11.
Signed would only be a problem if negative numbers wouldn't use two's complement. But all compilers use two's component.
The problem with unscoped enums (without specified underlying type) is the hypothetical value type, which cannot be detected through a trait. When you create the complement on such an enum, you usual leave that value type and enter UB-land.

**Comment by tobias-loew** [comment]
I'll close this issue, as we're currently having two PRs  (#25 and #31) working on it.
