### ISSUE TITLE
Missing word in documentation

### ISSUE THREAD

**Issue by andreasbuhr** [tobias-loew/flags#4]
Documentation states:

"All operators and functions are constexpr and use attribute whenever possible."

And I wonder which attributes is used whenever possible.

**Comment by tobias-loew** [comment]
that's in my .adoc file

All operators and functions are `constexpr` and use attribute `[[nodiscard]]` whenever possible.

using

All operators and functions are `constexpr` and use attribute `+[[nodiscard]]+` whenever possible.

works!
