### ISSUE TITLE
Documentation: How do I order everything but olives?

### ISSUE THREAD

**Issue by andreasbuhr** [tobias-loew/flags#6]
Looking at the documentation, at the example:

```
    // error: negative mask is not a pizza topping
    order_pizza(~pizza_toppings::olives);
```
How do I achieve what is intended here?. I.e., using the proposed Boost.Flags, how do I order "everything but olives"? Should I write `E{-1} & ~pizza_toppings::olives`? Maybe another helper function like `make_null` would be nice. Maybe named `make_all`?

**Comment by tobias-loew** [comment]
added pizza_toppings::all_toppings and conversation with the waiter
